version: "2"
linters:
  default: none
  enable:
    - copyloopvar
    - depguard
    - errcheck
    - gocyclo
    - godox
    - goprintffuncname
    - govet
    - ineffassign
    - misspell
    - noctx
    - prealloc
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - unconvert
    - unused
  settings:
    staticcheck:
      checks:
        - "all"
    gocyclo:
      # Minimal code complexity to report.
      # Default: 30 (but we recommend 10-20)
      min-complexity: 17
    godox:
      keywords:
        - FIXME
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/simplesurance/proteus
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
